//
//  PhotosWorker.swift
//  CleanFlickr
//
//  Created by Iñigo on 24/08/2018.
//  Copyright (c) 2018 Iñigo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PhotosWorker
{
    var photosStore: PhotosStoreProtocol
    
    init(photosStore: PhotosStoreProtocol)
    {
        self.photosStore = photosStore
    }


    func fetchPhotos(searchText: String, bbox: String, completionHandler: @escaping ([Photo]) -> Void)
    {
        photosStore.fetchPhotos(searchText: searchText, bbox: bbox, completionHandler: { (photos: () throws -> [Photo]) -> Void in
            do {
                let photos = try photos()
                DispatchQueue.main.async {
                    completionHandler(photos)
                }
            } catch {
                DispatchQueue.main.async {
                    completionHandler([])
                }
            }
        })
    }
}

enum PhotosStoreError: Equatable, Error
{
    case CannotFetch(String)
}

protocol PhotosStoreProtocol
{
    func fetchPhotos (searchText: String, bbox: String, completionHandler: @escaping (() throws -> [Photo]) -> Void)
}
