# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  before_all do |lane, options|
  	create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
  end

  lane :beta do |options|
    scheme = "CleanFlickr"
    if options[:scheme]
      scheme = options[:scheme]
    end
    configuration = options[:configuration]
    export_method = options[:export_method]
    disable_automatic_code_signing(path: "CleanFlickr.xcodeproj")
    gym(scheme: scheme, configuration: configuration, export_method:export_method, export_xcargs: "-allowProvisioningUpdates", output_name:"CleanFlickr.ipa")
    enable_automatic_code_signing(path: "CleanFlickr.xcodeproj")
  end
end
