//
//  PhotoDetailModels.swift
//  CleanFlickr
//
//  Created by Iñigo on 26/08/2018.
//  Copyright (c) 2018 Iñigo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PhotoDetail
{
  // MARK: Use cases
  
  enum GetPhoto
  {
    struct Request
    {
    }
    struct Response
    {
        var photo: Photo
    }
    struct ViewModel
    {
        struct displayedPhoto
        {
            var image: UIImage
        }
        var displayedPhoto: displayedPhoto
    }
  }
}
