//
//  PhotoDetailInteractor.swift
//  CleanFlickr
//
//  Created by Iñigo on 26/08/2018.
//  Copyright (c) 2018 Iñigo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoDetailBusinessLogic
{
  func getPhoto(request: PhotoDetail.GetPhoto.Request)
}

protocol PhotoDetailDataStore
{
  var photo: Photo! { get set }
}

class PhotoDetailInteractor: PhotoDetailBusinessLogic, PhotoDetailDataStore
{
  var presenter: PhotoDetailPresentationLogic?
  var photo: Photo!
    
  func getPhoto(request: PhotoDetail.GetPhoto.Request)
  {
    let response = PhotoDetail.GetPhoto.Response(photo: photo)
    presenter?.presentPhoto(response: response)
  }
}
