//
//  PhotoDetailPresenter.swift
//  CleanFlickr
//
//  Created by Iñigo on 26/08/2018.
//  Copyright (c) 2018 Iñigo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoDetailPresentationLogic
{
  func presentPhoto(response: PhotoDetail.GetPhoto.Response)
}

class PhotoDetailPresenter: PhotoDetailPresentationLogic
{
  weak var viewController: PhotoDetailDisplayLogic?
    
  func presentPhoto(response: PhotoDetail.GetPhoto.Response)
  {
    let photo = response.photo
    if let d = NSData(contentsOf: photo.url_m){
        let displayedPhoto = PhotoDetail.GetPhoto.ViewModel.displayedPhoto(image: UIImage(data: d as Data)!)
        let viewModel = PhotoDetail.GetPhoto.ViewModel.init(displayedPhoto: displayedPhoto)
        viewController?.displayPhoto(viewModel: viewModel)
    }
  }
}
