//
//  MapSearchPresenter.swift
//  CleanFlickr
//
//  Created by Iñigo on 24/08/2018.
//  Copyright (c) 2018 Iñigo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol MapSearchPresentationLogic
{
  func presentFetchedPhotos(response: MapSearch.FetchPhotos.Response)
}

class MapSearchPresenter: MapSearchPresentationLogic
{
  weak var viewController: MapSearchDisplayLogic?
  
  func presentFetchedPhotos(response: MapSearch.FetchPhotos.Response)
  {
    var displayedPhotos: [MapSearch.FetchPhotos.ViewModel.DisplayedPhoto] = []
    for photo in response.photos {
        var image = UIImage()
        if let d = NSData(contentsOf: (photo.url_t)){
            image = UIImage(data: d as Data)!
        }
    let coordinate = CLLocationCoordinate2D(latitude: photo.latitude, longitude: photo.longitude)
      let displayedPhoto = MapSearch.FetchPhotos.ViewModel.DisplayedPhoto(withTitle: photo.title, andUrl: photo.url_t, andCoordinate: coordinate, andBigImageUrl: photo.url_m, andImage: image)
        displayedPhotos.append(displayedPhoto)
    }
    let viewModel = MapSearch.FetchPhotos.ViewModel(displayedPhotos: displayedPhotos)
    viewController?.displayFetchedPhotos(viewModel: viewModel)
  }
}
