//
//  MapSearchModels.swift
//  CleanFlickr
//
//  Created by Iñigo on 24/08/2018.
//  Copyright (c) 2018 Iñigo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Foundation
import MapKit


enum MapSearch
{
  // MARK: Use cases
  
  enum FetchPhotos
  {

    struct Request
    {
    }
    struct Response
    {
        var photos: [Photo]
    }
    
    struct ViewModel
    {

        var displayedPhotos: [DisplayedPhoto]

        class DisplayedPhoto: NSObject, MKAnnotation{
            
            let title: String?
            let coordinate: CLLocationCoordinate2D
            let url: URL
            let bigImageUrl: URL
            let image: UIImage
            
            init(withTitle: String, andUrl: URL, andCoordinate: CLLocationCoordinate2D, andBigImageUrl: URL, andImage: UIImage) {
                
                title = withTitle
                url = andUrl
                coordinate = andCoordinate
                bigImageUrl = andBigImageUrl
                image = andImage
            }
        }
    }
  }
}
