//
//  MapSearchInteractor.swift
//  CleanFlickr
//
//  Created by Iñigo on 24/08/2018.
//  Copyright (c) 2018 Iñigo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapSearchBusinessLogic
{
    func fetchPhotos(searchText: String, bbox: String, request: MapSearch.FetchPhotos.Request)
}

protocol MapSearchDataStore
{
    var photos: [Photo]? { get }
}

class MapSearchInteractor: MapSearchBusinessLogic, MapSearchDataStore
{
    
  var presenter: MapSearchPresentationLogic?
  var photosWorker = PhotosWorker(photosStore: PhotosAPI())
  var photos: [Photo]?

  func fetchPhotos(searchText: String, bbox: String, request: MapSearch.FetchPhotos.Request)
  {
    photosWorker.fetchPhotos(searchText: searchText, bbox: bbox, completionHandler: {(photos) -> Void in
        self.photos = photos
        let response = MapSearch.FetchPhotos.Response(photos: photos)
        self.presenter?.presentFetchedPhotos(response: response)
    })
  }
}
